apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: my-app-sprintboot1
    appstudio.openshift.io/component: devfile-sample-java-springboot-basic-yv4k
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic-yv4k
  namespace: eyuen-tenant
spec:
  url: https://github.com/devfile-samples/devfile-sample-java-springboot-basic
